version: "3.4"

services:
  database:
    container_name: chevereto${VERSION}-${PROJECT}-php${PHP}_database
    image: mariadb:focal
    networks:
      - chevereto
    volumes:
      - database:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chevereto
      MYSQL_USER: chevereto
      MYSQL_PASSWORD: user_database_password

  php:
    container_name: chevereto${VERSION}-${PROJECT}-php${PHP}
    image: ghcr.io/chevereto/docker:${VERSION}-php${PHP}
    depends_on:
      - database
    networks:
      - chevereto
    volumes:
      - storage:/var/www/html/images/
      - assets:/var/www/html/_assets/
      - app:/var/www/html/
    ports:
      - 9000
    restart: always
    healthcheck:
      test: ["CMD", "stat", "/var/CONTAINER_STARTED_PLACEHOLDER"]
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 15s
    environment:
      CHEVERETO_TAG: ${VERSION}
      CHEVERETO_LICENSE: ${LICENSE}
      CHEVERETO_DB_HOST: database
      CHEVERETO_DB_USER: chevereto
      CHEVERETO_DB_PASS: user_database_password
      CHEVERETO_DB_PORT: 3306
      CHEVERETO_DB_NAME: chevereto
      CHEVERETO_HTTPS: 0
      CHEVERETO_ASSET_STORAGE_TYPE: local
      CHEVERETO_ASSET_STORAGE_URL: http://localhost:${FLAG_DEMO}${VERSION_DOTLESS}${PHP_DOTLESS}/_assets/
      CHEVERETO_ASSET_STORAGE_BUCKET: /var/www/html/_assets/

  server:
    container_name: chevereto${VERSION}-${PROJECT}-php${PHP}_server
    image: httpd:2.4
    depends_on:
      - php
    networks:
      - chevereto
    volumes:
      - storage:/var/www/html/images/
      - assets:/var/www/html/_assets/
      - app:/var/www/html/
      - type: bind
        source: ${PWD}/httpd.conf
        target: /usr/local/apache2/conf/httpd.conf
    ports:
      - ${FLAG_DEMO}${VERSION_DOTLESS}${PHP_DOTLESS}:80
    restart: always

volumes:
  database:
  assets:
  storage:
  app:

networks:
  chevereto:
