version: "3.2"

services:
  database:
    container_name: chevereto4.0-dev-php8.0_database
    image: mariadb:focal
    networks:
      - chevereto
    volumes:
      - database:/var/lib/mysql
    ports:
      - 40806:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chevereto
      MYSQL_USER: chevereto
      MYSQL_PASSWORD: user_database_password

  chevereto:
    container_name: chevereto4.0-dev-php8.0
    image: ghcr.io/chevereto/docker:4.0-php8.0
    depends_on:
      - database
    networks:
      - chevereto
    volumes:
      - storage:/var/www/html/images/
      - assets:/var/www/html/_assets/
      - app:/var/www/html/
      - type: bind
        source: ${SOURCE}
        target: /var/www/chevereto
    ports:
      - 44080:80
    restart: always
    healthcheck:
      test: ["CMD", "stat", "/var/CONTAINER_STARTED_PLACEHOLDER"]
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 15s
    environment:
      CHEVERETO_TAG: dev
      CHEVERETO_DB_HOST: database
      CHEVERETO_DB_USER: chevereto
      CHEVERETO_DB_PASS: user_database_password
      CHEVERETO_DB_PORT: 3306
      CHEVERETO_DB_NAME: chevereto
      CHEVERETO_HTTPS: 0
      CHEVERETO_ASSET_STORAGE_TYPE: local
      CHEVERETO_ASSET_STORAGE_URL: http://localhost:44080/_assets/
      CHEVERETO_ASSET_STORAGE_BUCKET: /var/www/html/_assets/

volumes:
  database:
  assets:
  storage:
  app:

networks:
  chevereto:
