version: "3.2"

services:
  chv-database:
    container_name: chevereto-v4-dev_httpd-php_database
    image: mariadb:focal
    networks:
      - chv-network
    volumes:
      - chv-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chevereto
      MYSQL_USER: chevereto
      MYSQL_PASSWORD: user_database_password

  chv-bootstrap:
    container_name: chevereto-v4-dev_httpd-php_bootstrap
    image: ghcr.io/chevereto/httpd-php:4.0
    networks:
      - chv-network
    volumes:
      - chv-storage:/var/www/html/images/
      - chv-assets:/var/www/html/_assets/
      - chv-app:/var/www/html/
      - type: bind
        source: ${SOURCE}
        target: /var/www/chevereto
    ports:
      - 8009:80
    restart: always
    environment:
      CHEVERETO_TAG: dev
      CHEVERETO_DB_HOST: chv-database
      CHEVERETO_DB_USER: chevereto
      CHEVERETO_DB_PASS: user_database_password
      CHEVERETO_DB_PORT: 3306
      CHEVERETO_DB_NAME: chevereto
      CHEVERETO_HTTPS: 0
      CHEVERETO_ASSET_STORAGE_TYPE: local
      CHEVERETO_ASSET_STORAGE_URL: http://localhost:8009/_assets/
      CHEVERETO_ASSET_STORAGE_BUCKET: /var/www/html/_assets/

volumes:
  chv-data:
  chv-assets:
  chv-storage:
  chv-app:

networks:
  chv-network:
